/**
 * Choosing the two typefaces.
 *
 * The same shape as the palettes next door: a `data-` attribute on the root
 * names the choice, and `fonts.css` — generated by `pnpm fonts` — says what
 * stack that name means. Nothing in the components knows a font's name.
 *
 * `system` is the absence of a choice rather than a font of its own, so it
 * sets no attribute and the default in `tokens.css` stands.
 */

import type { MonoFont, UiFont } from "../bindings";

export type FontChoice<Id> = { id: Id; label: string };

/** Sans faces for the interface. */
export const UI_FONTS: FontChoice<UiFont>[] = [
  { id: "system", label: "System" },
  { id: "inter", label: "Inter" },
  { id: "geist", label: "Geist" },
  { id: "figtree", label: "Figtree" },
  { id: "ibm-plex-sans", label: "IBM Plex Sans" },
  { id: "roboto", label: "Roboto" },
];

/** Monospaced faces for code, paths and sizes. */
export const MONO_FONTS: FontChoice<MonoFont>[] = [
  { id: "system", label: "System" },
  { id: "jetbrains-mono", label: "JetBrains Mono" },
  { id: "fira-code", label: "Fira Code" },
  { id: "geist-mono", label: "Geist Mono" },
  { id: "ibm-plex-mono", label: "IBM Plex Mono" },
];

const UI_IDS = new Set(UI_FONTS.map((font) => font.id));
const MONO_IDS = new Set(MONO_FONTS.map((font) => font.id));

export function isUiFont(value: string | null | undefined): value is UiFont {
  return UI_IDS.has(value as UiFont);
}

export function isMonoFont(value: string | null | undefined): value is MonoFont {
  return MONO_IDS.has(value as MonoFont);
}

/**
 * Anything unrecognised — a settings file written by a newer version — falls
 * back to the system face rather than to nothing.
 */
export function resolveFonts(
  ui: string | null | undefined,
  mono: string | null | undefined,
): { ui: UiFont; mono: MonoFont } {
  return {
    ui: isUiFont(ui) ? ui : "system",
    mono: isMonoFont(mono) ? mono : "system",
  };
}

export function applyFonts(ui: UiFont, mono: MonoFont): void {
  const root = document.documentElement;
  if (ui === "system") delete root.dataset.fontUi;
  else root.dataset.fontUi = ui;

  if (mono === "system") delete root.dataset.fontMono;
  else root.dataset.fontMono = mono;
}
