/**
 * Regenerates `src/components/common/icons.ts`.
 *
 * Icons are referred to by name — that is how the tool registry and the item
 * types name them — but resolving those names against `lucide-react` at
 * runtime pulls every icon it has into the bundle, about a megabyte for the
 * three dozen actually drawn. So the names are collected from the source and
 * written out as explicit imports the bundler can see.
 *
 * Run with `pnpm icons`. `Icon.test.ts` fails if a name in use is missing.
 */

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const SRC = fileURLToPath(new URL("../src", import.meta.url));
const OUT = join(SRC, "components/common/icons.ts");

function sourceFiles(dir) {
  return readdirSync(dir).flatMap((entry) => {
    // This checkout sits on exFAT, where macOS writes AppleDouble sidecars.
    if (entry.startsWith("._")) return [];
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return sourceFiles(path);
    return /\.tsx?$/.test(path) ? [path] : [];
  });
}

const names = new Set();
for (const file of sourceFiles(SRC)) {
  const source = readFileSync(file, "utf8");
  for (const match of source.matchAll(/<Icon\s[^>]*name="([a-z0-9-]+)"/g)) names.add(match[1]);
  // The ternary form: name={condition ? "a" : "b"}
  for (const match of source.matchAll(/name={[^}]*\?\s*"([a-z0-9-]+)"\s*:\s*"([a-z0-9-]+)"}/g)) {
    names.add(match[1]);
    names.add(match[2]);
  }
  for (const match of source.matchAll(/icon: "([a-z0-9-]+)"/g)) names.add(match[1]);
}

const pascal = (kebab) =>
  kebab
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");

const lucide = await import("lucide-react");
const sorted = [...names].sort();
const missing = sorted.filter((name) => !(pascal(name) in lucide));
if (missing.length > 0) {
  console.error(`lucide has no icon called: ${missing.join(", ")}`);
  process.exit(1);
}

writeFileSync(
  OUT,
  `// Every icon the application draws, imported by name.
//
// Generated by \`pnpm icons\`. Do not edit by hand: \`Icon.test.ts\` fails if a
// name used anywhere in the source is missing here.
//
// Explicit rather than resolved at runtime, because looking names up against
// \`lucide-react\` puts the whole icon set in the bundle.

import type { LucideIcon } from "lucide-react";
import {
${sorted.map((name) => `  ${pascal(name)},`).join("\n")}
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
${sorted.map((name) => `  "${name}": ${pascal(name)},`).join("\n")}
};
`,
);
// Biome owns the formatting of everything in src/, generated or not.
execFileSync("pnpm", ["biome", "format", "--write", OUT], { stdio: "ignore" });
console.log(`wrote ${sorted.length} icons to src/components/common/icons.ts`);
