// Every icon the application draws, imported by name.
//
// Resolving icons dynamically out of `lucide-react` pulls the whole set into
// the bundle — around a megabyte for the thirty-odd actually used. Listing
// them lets the bundler drop the rest.
//
// Generated-ish: `icons.test.ts` fails if a name used anywhere is missing here.

import type { LucideIcon } from "lucide-react";
import {
  Asterisk,
  Bot,
  Box,
  ChevronDown,
  CircleAlert,
  Code2,
  Diamond,
  Feather,
  FolderGit2,
  GitBranch,
  Globe,
  House,
  Info,
  Library,
  Link,
  MousePointer2,
  Orbit,
  Package,
  Pi,
  Play,
  RefreshCw,
  ScrollText,
  Search,
  Send,
  Settings,
  Shapes,
  Share2,
  Sparkles,
  Star,
  StarOff,
  Terminal,
  TerminalSquare,
  Unlink,
  Waves,
  Wrench,
  X,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  asterisk: Asterisk,
  bot: Bot,
  box: Box,
  "chevron-down": ChevronDown,
  "circle-alert": CircleAlert,
  "code-2": Code2,
  diamond: Diamond,
  feather: Feather,
  "folder-git-2": FolderGit2,
  "git-branch": GitBranch,
  globe: Globe,
  house: House,
  info: Info,
  library: Library,
  link: Link,
  "mouse-pointer-2": MousePointer2,
  orbit: Orbit,
  package: Package,
  pi: Pi,
  play: Play,
  "refresh-cw": RefreshCw,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  shapes: Shapes,
  "share-2": Share2,
  sparkles: Sparkles,
  star: Star,
  "star-off": StarOff,
  terminal: Terminal,
  "terminal-square": TerminalSquare,
  unlink: Unlink,
  waves: Waves,
  wrench: Wrench,
  x: X,
};
