//! Adapter layer: turns `skills-core` into Tauri commands.
//!
//! Nothing in here makes a domain decision. It resolves paths the platform owns,
//! holds shared state, maps core errors onto a serializable shape, and adapts the
//! core's progress callback onto a Tauri channel.

mod commands;
mod error;

pub use error::CommandError;

use tauri_specta::{Builder, collect_commands};

/// The command surface, in one place. `main` mounts it; the bindings test
/// exports it. Both go through here so they cannot drift apart.
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::capabilities::probe_capabilities
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("skills_hub_lib=info")),
        )
        .init();

    let builder = specta_builder();

    let run = tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!());

    if let Err(err) = run {
        tracing::error!(%err, "fatal: could not start the application");
        std::process::exit(1);
    }
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::specta_builder;

    /// Regenerates `src/bindings.ts`. The file is committed; CI runs this and
    /// fails if the working tree is dirty afterwards, which is what stops the
    /// hand-written frontend types from drifting off the command signatures.
    #[test]
    fn export_typescript_bindings() {
        let config = specta_typescript::Typescript::new().header(
            "// @generated by tauri-specta. Do not edit by hand.\n\
             // Run `cargo test -p skills-hub` to regenerate.\n",
        );

        specta_builder()
            .export(config, "../src/bindings.ts")
            .expect("exporting TypeScript bindings should succeed");
    }
}
