// @generated by tauri-specta. Do not edit by hand.
// Run `cargo test -p skills-hub` to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	probeCapabilities: () => typedError<Capabilities, CommandError>(__TAURI_INVOKE("probe_capabilities")),
	getSettings: () => typedError<SettingsView, CommandError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Replaces the settings wholesale.
	 * 
	 *  The frontend sends the whole document because it holds the authoritative
	 *  copy between edits; a patch API would need a merge on both sides.
	 */
	updateSettings: (settings: AppSettings) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("update_settings", { settings })),
	setToolOverride: (toolId: string, overrides: ToolOverride) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("set_tool_override", { toolId, overrides })),
	/**  Points the store at a folder, creating it if need be. */
	setMetadataFolder: (folder: string) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("set_metadata_folder", { folder })),
	addProjectWorkspace: (path: string, name: string | null) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("add_project_workspace", { path, name })),
	removeProjectWorkspace: (id: string) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("remove_project_workspace", { id })),
	/**
	 *  The last scan's result, without touching the disk.
	 * 
	 *  What the window asks for when it opens or reloads.
	 */
	getSnapshot: () => typedError<{
	items: ItemMetadata[],
	plugins: PluginSource[],
	brokenSymlinks: BrokenSymlink[],
	warnings: ScanWarning[],
	/**  When the scan ran, as RFC 3339 — the same form the notes use. */
	scannedAt: string,
	/**
	 *  Increments with every scan.
	 * 
	 *  The frontend keys its derived state on this, so "a scan happened"
	 *  invalidates everything at once rather than through a dozen
	 *  hand-maintained call sites.
	 */
	version: number,
	/**  Notes kept for items that are no longer on disk. */
	orphanCount: number,
} | null, CommandError>(__TAURI_INVOKE("get_snapshot")),
	/**
	 *  Walks every configured folder and records what is there.
	 * 
	 *  Runs on a blocking thread: the work is filesystem-bound, and the core is
	 *  deliberately synchronous so that it stays testable.
	 */
	rescan: (options: RescanOptions, onProgress: Channel<Progress>) => typedError<LibrarySnapshot, CommandError>(__TAURI_INVOKE("rescan", { options, onProgress })),
	/**  Notes kept for items that are no longer on disk. */
	listOrphanedMetadata: () => typedError<Orphan[], CommandError>(__TAURI_INVOKE("list_orphaned_metadata")),
	/**  Removes orphaned notes the user has decided to let go of. */
	forgetOrphanedMetadata: (entryIds: string[]) => typedError<number, CommandError>(__TAURI_INVOKE("forget_orphaned_metadata", { entryIds })),
	readItemContent: (entryId: string) => typedError<ItemContent, CommandError>(__TAURI_INVOKE("read_item_content", { entryId })),
	/**
	 *  Saves an edit to an item's own file.
	 * 
	 *  The scanner reads name and description out of the file, so the note is
	 *  refreshed from it straight away rather than waiting for the next scan.
	 */
	writeItemContent: (entryId: string, content: string) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("write_item_content", { entryId, content })),
	setItemEnabled: (entryId: string, enabled: boolean) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_enabled", { entryId, enabled })),
	setItemFavorite: (entryId: string, favorite: boolean) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_favorite", { entryId, favorite })),
	setItemTags: (entryId: string, tags: string[]) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_tags", { entryId, tags })),
	setItemCollections: (entryId: string, collections: string[]) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_collections", { entryId, collections })),
	/**  Makes a global item visible inside a project, by symlink. */
	linkIntoProject: (entryId: string, projectId: string) => typedError<string, CommandError>(__TAURI_INVOKE("link_into_project", { entryId, projectId })),
	/**  Removes a link from a project, leaving what it pointed at alone. */
	unlinkFromProject: (entryId: string) => typedError<null, CommandError>(__TAURI_INVOKE("unlink_from_project", { entryId })),
	/**  Deletes an item from disk, and its note with it. */
	deleteItem: (entryId: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_item", { entryId })),
	/**  Every tool and where it looks, so the tools page can show what was found. */
	describeTools: () => typedError<ToolReport[], CommandError>(__TAURI_INVOKE("describe_tools")),
	checkPath: (path: string) => __TAURI_INVOKE<PathStatus>("check_path", { path }),
	/**
	 *  Adds a tool the application does not ship.
	 * 
	 *  For something new, or something whose layout is different enough that
	 *  changing paths on an existing entry would be a lie about which tool it is.
	 */
	addCustomTool: (id: string, paths: Partial<{ [key in ItemType]: string }>) => typedError<null, CommandError>(__TAURI_INVOKE("add_custom_tool", { id, paths })),
	/**  Removes a tool the user added. Nothing on disk is touched. */
	removeCustomTool: (toolId: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_custom_tool", { toolId })),
	getDiscoverCatalog: () => typedError<DiscoverCatalog, CommandError>(__TAURI_INVOKE("get_discover_catalog")),
	/**
	 *  Asks a registry which repositories hold a skill by this name.
	 * 
	 *  skills.sh indexes skills across GitHub and counts how often each is
	 *  installed, which is the one ranking signal on offer and the reason to ask
	 *  it rather than search GitHub directly. What comes back names a repository,
	 *  so a hit becomes an ordinary watched source — and everything downstream,
	 *  including updating and restoring, is unaffected.
	 * 
	 *  A registry being unreachable is reported rather than swallowed: unlike the
	 *  star count, this is the whole answer to what the user asked.
	 */
	searchRegistry: (query: string) => typedError<RegistryHit[], CommandError>(__TAURI_INVOKE("search_registry", { query })),
	/**
	 *  Clones a repository, records everything installable in it, and asks GitHub
	 *  how many stars it has.
	 */
	discoverAddSource: (repoUrl: string, refName: string, subpath: string) => typedError<DiscoverCatalog, CommandError>(__TAURI_INVOKE("discover_add_source", { repoUrl, refName, subpath })),
	/**  Clones a watched repository again and replaces what was known about it. */
	discoverRefreshSource: (sourceId: string) => typedError<DiscoverCatalog, CommandError>(__TAURI_INVOKE("discover_refresh_source", { sourceId })),
	discoverRemoveSource: (sourceId: string) => typedError<DiscoverCatalog, CommandError>(__TAURI_INVOKE("discover_remove_source", { sourceId })),
	/**  Installs one item and records where it came from. */
	installFromGithub: (spec: InstallSpec) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("install_from_github", { spec })),
	/**
	 *  Asks every named item's remote whether it has moved on.
	 * 
	 *  In parallel: each is a separate `ls-remote` and they wait on the network,
	 *  not on each other. A check that fails is reported as a failure for that
	 *  item rather than sinking the rest.
	 */
	checkForUpdates: (entryIds: string[], onProgress: Channel<CheckProgress>) => typedError<UpdateCheck[], CommandError>(__TAURI_INVOKE("check_for_updates", { entryIds, onProgress })),
	/**
	 *  Fetches the other version and works out what differs, without touching the
	 *  local copy.
	 */
	prepareReview: (entryId: string, mode: ReviewMode) => typedError<ReviewHandle, CommandError>(__TAURI_INVOKE("prepare_review", { entryId, mode })),
	/**
	 *  Replaces the local copy with the version the review showed.
	 * 
	 *  A review whose diff showed nothing still advances the recorded commit, so
	 *  the item stops being reported as stale for a change that was not about it.
	 */
	applyReview: (reviewId: string) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("apply_review", { reviewId })),
	/**  Throws a review away, and the clone it was holding with it. */
	cancelReview: (reviewId: string) => typedError<null, CommandError>(__TAURI_INVOKE("cancel_review", { reviewId })),
	/**
	 *  Reads a tool's own session history and reports what has actually been used.
	 * 
	 *  Only Claude Code and Codex keep anything to read. For everything else this
	 *  returns nothing, and the dashboard falls back to what a file looks like.
	 * 
	 *  This can be hundreds of megabytes, so it is asked for rather than done on
	 *  every scan.
	 */
	loadUsage: (toolId: string, onProgress: Channel<UsageProgress>) => typedError<{ [key in string]: UsageStats }, CommandError>(__TAURI_INVOKE("load_usage", { toolId, onProgress })),
	/**  Costs, prune suggestions and overlaps, over whatever was last scanned. */
	computeDashboard: (usageByEntry: { [key in string]: UsageStats }) => typedError<DashboardReport, CommandError>(__TAURI_INVOKE("compute_dashboard", { usageByEntry })),
	/**  Waves a suggestion away without touching the item behind it. */
	disregard: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("disregard", { id })),
	/**  Takes a suggestion off the dismissed list. */
	undisregard: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("undisregard", { id })),
	listDisregarded: () => typedError<string[], CommandError>(__TAURI_INVOKE("list_disregarded")),
	listMcpServers: () => typedError<McpReport, CommandError>(__TAURI_INVOKE("list_mcp_servers")),
	/**
	 *  Enables or disables a whole plugin bundle through its own tool's settings.
	 * 
	 *  A bundled item cannot be toggled on its own — the bundle is the unit the
	 *  owning tool understands — so this is the only way to switch one off.
	 */
	setPluginEnabled: (toolId: string, pluginId: string, enabled: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_plugin_enabled", { toolId, pluginId, enabled })),
	/**  Creates a collection, or renames one. */
	saveCollection: (collection: CollectionDef) => typedError<CollectionDef[], CommandError>(__TAURI_INVOKE("save_collection", { collection })),
	/**
	 *  Removes a collection, and takes it out of every item that was in it.
	 * 
	 *  Scrubbing the notes afterwards is idempotent and re-runnable, so a failure
	 *  halfway through leaves nothing inconsistent — the next attempt finishes
	 *  the job.
	 */
	deleteCollection: (collectionId: string) => typedError<CollectionDef[], CommandError>(__TAURI_INVOKE("delete_collection", { collectionId })),
	/**  Puts an item into a collection, or takes it out again. */
	setItemInCollection: (entryId: string, collectionId: string, member: boolean) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_in_collection", { entryId, collectionId, member })),
	/**
	 *  Shows a file in Finder, Explorer or the desktop's file manager.
	 * 
	 *  `resolve_symlink` follows a link to where it really points, which is what
	 *  someone wants when they mean to edit the skill rather than inspect the link.
	 */
	revealInFileManager: (path: string, resolveSymlink: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("reveal_in_file_manager", { path, resolveSymlink })),
	/**  Opens a path with whatever the operating system uses for it. */
	openPath: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("open_path", { path })),
};

/* Types */
/**  Everything the application remembers between runs. */
export type AppSettings = {
	schemaVersion?: number,
	/**  Where the metadata notes live. Empty until the user has chosen. */
	metadataFolder?: string | null,
	toolOverrides?: { [key in string]: ToolOverride },
	/**  Tools the user added themselves. */
	customTools?: ToolConfig[],
	projectWorkspaces?: ProjectWorkspace[],
	/**
	 *  Collection definitions only. Membership lives in each item's note, so
	 *  there is one answer to "is this item in that collection" rather than two
	 *  that can disagree.
	 */
	collections?: CollectionDef[],
	sectionOrder?: string[],
	showEmptySidebarRows?: boolean,
	defaultSortOrder?: SortOrder,
	defaultEnabledFilter?: EnabledFilter,
	theme?: ThemePref,
};

/**  A symlink whose target no longer resolves. */
export type BrokenSymlink = {
	path: string,
	/**  The link target exactly as written, which may be relative. */
	target: string,
	/**  That target resolved to an absolute path. */
	targetPath: string,
	tool: string,
	type: ItemType,
	projectId: string | null,
};

export type Capabilities = {
	/**  Home directory, as the scanner will expand `~`. */
	home: string,
	/**
	 *  Whether this process may create symlinks. False on Windows without
	 *  Developer Mode, which disables linking a global skill into a project.
	 */
	symlinksSupported: boolean,
	appVersion: string,
	platform: string,
};

/**  Progress through a bulk check. */
export type CheckProgress = {
	done: number,
	total: number,
};

/**
 *  A named grouping of items.
 * 
 *  Only the definition lives in settings. Which items belong is recorded in
 *  each item's own note, so there is one answer to the question rather than
 *  two that can disagree — and `contains(collections, "work")` in Dataview is
 *  the real answer, not a shadow of it.
 */
export type CollectionDef = {
	id: string,
	name: string,
	icon?: string | null,
};

export type CommandError = {
	code: string,
	message: string,
};

/**  What happened to one of a skill's other files. */
export type CompanionChange = {
	/**  Path relative to the skill's folder. */
	path: string,
	status: CompanionStatus,
};

export type CompanionStatus = "added" | "removed" | "modified";

/**  Everything the dashboard shows. */
export type DashboardReport = {
	costs: ItemCost[],
	prune: PruneCandidate[],
	overlaps: Overlap[],
	/**  Totals across everything enabled. */
	totalSourceChars: number,
	totalAvailableChars: number,
	totalInvocationChars: number,
};

/**  One rendered line of a diff. */
export type DiffLine = {
	/**  `+` added, `-` removed, ` ` unchanged. */
	marker: string,
	/**  Line number in whichever side this line belongs to. */
	number: number | null,
	segments: Segment[],
};

/**  How much changed, for a summary before anyone reads the detail. */
export type DiffStats = {
	added: number,
	removed: number,
};

/**  Everything the user is watching, and what was found in it. */
export type DiscoverCatalog = {
	sources?: DiscoverSource[],
	entries?: DiscoverEntry[],
};

/**  One installable item found in a repository. */
export type DiscoverEntry = {
	id: string,
	/**  The source it came from. */
	sourceId: string,
	repoUrl: string,
	refName: string,
	/**  Where in the repository this item is. */
	subpath: string,
	type: ItemType,
	name: string,
	description: string,
	tags: string[],
	/**  The commit it was found at. */
	commit: string,
	/**  The manifest's text, cached so a preview needs no second clone. */
	manifest: string,
	discoveredAt: string,
};

/**  A repository the user is watching for installable items. */
export type DiscoverSource = {
	id: string,
	repoUrl: string,
	/**  Empty means the default branch. */
	refName: string,
	/**  Empty means the whole repository. */
	subpath: string,
	addedAt: string,
	/**  Stars, and when that was last asked. `None` means never asked. */
	stars?: number | null,
	starsFetchedAt?: string | null,
};

/**  What a scan found on disk, before any user metadata is attached. */
export type DiscoveredItem = {
	entryId: string,
	/**  The `SKILL.md` for a folder skill, otherwise the file itself. */
	sourcePath: string,
	/**
	 *  `source_path` with symlinks resolved. Equal to `source_path` when it is
	 *  not a link.
	 */
	realPath: string,
	tool: string,
	type: ItemType,
	/**  `None` means the global (home directory) scope. */
	projectId: string | null,
	/**  `None` means the item was not shipped inside an installed plugin. */
	pluginId: string | null,
	name: string,
	description: string,
	/**  Derived purely from which folder the item physically sits in. */
	enabled: boolean,
	/**
	 *  When the item's own file was last written, as RFC 3339.
	 * 
	 *  `None` when it could not be read — a dangling link, or a filesystem
	 *  that does not record it.
	 */
	modified: string | null,
};

export type EnabledFilter = "all" | "enabled" | "disabled";

/**
 *  One declared frontmatter key, in the order it appeared.
 * 
 *  Order is preserved so the detail view can show the block the way the author
 *  wrote it, rather than alphabetised.
 */
export type Field = {
	key: string,
	value: string,
};

/**  Provenance for an item installed through the application. */
export type InstallSource = {
	sourceRepo: string | null,
	/**  Empty string means "track the default branch". */
	sourceRef: string | null,
	/**  Empty string means the repository root is the item. */
	sourceSubpath: string | null,
	sourceCommit: string | null,
};

/**  Where an item from a repository should be installed. */
export type InstallSpec = {
	repoUrl: string,
	refName: string,
	subpath: string,
	toolId: string,
	type: ItemType,
	/**  `None` installs into the home directory. */
	projectId: string | null,
};

/**  One item's file, as the detail view needs it. */
export type ItemContent = {
	raw: string,
	/**  Every declared frontmatter key, in the order the author wrote them. */
	frontmatter: Field[],
	/**  Everything after the frontmatter. */
	body: string,
	bytes: number | null,
	/**  When the file was last written, as RFC 3339. */
	modified: string | null,
	isSymlink: boolean,
	realPath: string,
	/**  The other files in a skill's folder, if it has any. */
	siblingFiles: SiblingFile[],
};

/**  What one item costs. */
export type ItemCost = {
	entryId: string,
	name: string,
	tool: string,
	type: ItemType,
	/**  The whole file. */
	sourceChars: number,
	/**
	 *  Name and description: what a tool carries every turn.
	 * 
	 *  `None` for commands and rules, whose loading is not modelled.
	 */
	availableChars: number | null,
	/**  The instructions loaded once the item is invoked. */
	invocationChars: number | null,
	/**  When the file was last written. */
	modified: string | null,
};

/**  A discovered item plus everything the user has said about it. */
export type ItemMetadata = {
	tags: string[],
	favorite: boolean,
	collections: string[],
} & DiscoveredItem & InstallSource;

/**  What a discovered file *is*, from the point of view of the tool that reads it. */
export type ItemType = "skill" | "agent" | "command" | "rule";

/**  Everything the user interface needs after a scan. */
export type LibrarySnapshot = {
	items: ItemMetadata[],
	plugins: PluginSource[],
	brokenSymlinks: BrokenSymlink[],
	warnings: ScanWarning[],
	/**  When the scan ran, as RFC 3339 — the same form the notes use. */
	scannedAt: string,
	/**
	 *  Increments with every scan.
	 * 
	 *  The frontend keys its derived state on this, so "a scan happened"
	 *  invalidates everything at once rather than through a dozen
	 *  hand-maintained call sites.
	 */
	version: number,
	/**  Notes kept for items that are no longer on disk. */
	orphanCount: number,
};

export type McpConfigFormat = "json" | "toml";

/**  Every MCP server every tool is configured with. */
export type McpReport = {
	servers: McpServer[],
	warnings: ScanWarning[],
};

/**  One configured server, and where that configuration lives. */
export type McpServer = {
	id: string,
	name: string,
	tool: string,
	/**  `None` is the global scope. */
	projectId: string | null,
	config: McpServerConfig,
	sourcePath: string,
};

/**  How a server is started, or where it is reached. */
export type McpServerConfig = {
	command?: string | null,
	args?: string[],
	/**  Environment, often holding a token — never shown unmasked by default. */
	env?: { [key in string]: string },
	url?: string | null,
	type?: string | null,
};

/**  A note whose item is no longer on disk. */
export type Orphan = {
	entryId: string,
	name: string,
	tool: string,
	orphanedAt: string,
	hasUserData: boolean,
	path: string,
};

/**  Two items that look like they are after the same request. */
export type Overlap = {
	a: string,
	b: string,
	aName: string,
	bName: string,
	/**  Stable across the pair, whichever order they come in. */
	pairId: string,
	reason: OverlapReason,
	/**  How alike their descriptions are, from 0 to 1. */
	similarity: number | null,
};

export type OverlapReason = 
/**  The same name and type: an outright collision. */
"same-name" | 
/**  Descriptions alike enough to compete. */
"similar-description";

/**
 *  Whether a path a user is typing actually exists.
 * 
 *  Checked as they type rather than on save, because a path that is nearly
 *  right looks exactly like one that is right.
 */
export type PathStatus = {
	expanded: string,
	exists: boolean,
	isDirectory: boolean,
};

/**
 *  A plugin bundle installed into one of the tools.
 * 
 *  The items inside it are scanned like any others, but are not individually
 *  toggleable: a bundle is enabled or disabled as a whole, by its own tool.
 */
export type PluginSource = {
	id: string,
	name: string,
	/**  The marketplace or registry the bundle came from. */
	group: string | null,
	/**  Where this version is installed. */
	path: string,
	toolId: string,
	enabled: boolean,
	/**  Repository from the bundle manifest, GitHub only. */
	repoUrl: string | null,
};

/**
 *  How far along a scan is.
 * 
 *  Reported as it happens so a long scan shows a count rather than a spinner.
 */
export type Progress = { stage: "scanning"; 
/**  The tool or project currently being walked. */
source: string; done: number; total: number } | { stage: "recording"; done: number; total: number } | { stage: "finished" };

/**  A folder outside the home directory that is also scanned for items. */
export type ProjectWorkspace = {
	id: string,
	name: string,
	path: string,
};

/**  A suggestion, and why it is being made. */
export type PruneCandidate = {
	entryId: string,
	name: string,
	tool: string,
	reason: PruneReason,
	sourceChars: number,
	lastUsed: string | null,
	modified: string | null,
};

export type PruneReason = 
/**  The tool's own history says it has never run. */
"never-used" | 
/**  It has run, but not for a long time. */
"not-used-lately" | 
/**  No usage to go on, so: large and long untouched. */
"large-and-old";

/**  What the registry knows about one skill. */
export type RegistryHit = {
	/**  `owner/repo/skill`, as the registry identifies it. */
	id: string,
	/**  The GitHub repository it lives in, as `owner/repo`. */
	source: string,
	/**  Its name within that repository. */
	name: string,
	/**
	 *  How many times it has been installed through the registry.
	 * 
	 *  The only ranking signal on offer, and the reason to consult a registry
	 *  rather than search GitHub directly. A `u32` because this crosses into
	 *  JavaScript, which has no wider integer — and the busiest skill on the
	 *  registry is six figures.
	 */
	installs: number,
	/**  The repository, as something git can clone. */
	repoUrl: string,
};

/**  What to scan. */
export type RescanOptions = {
	/**
	 *  Skip the plugin bundle walk. Only for a targeted refresh; a full scan
	 *  that left bundles out would look to the store like every bundled item
	 *  had been deleted.
	 */
	skipPlugins?: boolean,
};

export type ResolvedPath = {
	type: ItemType,
	/**  As configured, with a leading `~` still in it. */
	configured: string,
	/**  The same path, expanded against this machine. */
	path: string,
	exists: boolean,
	/**  The scope this path belongs to: the home directory, or a project. */
	projectId: string | null,
};

/**  What an update or restore would do. */
export type ReviewHandle = {
	/**  Pass this back to apply or cancel. */
	reviewId: string,
	entryId: string,
	lines: DiffLine[],
	stats: DiffStats,
	companions: CompanionChange[],
	/**  The commit that would be recorded. */
	commit: string,
	/**  The repository moved on, but nothing about this item did. */
	unchanged: boolean,
};

/**  Which version of a tracked item to fetch. */
export type ReviewMode = 
/**  Whatever the remote has now. */
"update" | 
/**  The commit it was installed at. */
"restore";

/**
 *  An extra rule location beyond the tool's single configured one.
 * 
 *  `single_file` is recorded when the entry is added and never re-derived: a
 *  disabled single-file rule no longer exists at its own path, so asking the
 *  filesystem later would give the wrong answer.
 */
export type RulePathEntry = {
	path: string,
	singleFile: boolean,
};

/**
 *  Something the scan could not do.
 * 
 *  Carried through to the UI rather than logged and forgotten, because a scan
 *  that silently returned less than it should must never be allowed to look
 *  like a scan that found nothing — that is the difference between a warning
 *  and deleting the user's metadata.
 */
export type ScanWarning = {
	path: string,
	tool: string | null,
	message: string,
	kind: ScanWarningKind,
};

export type ScanWarningKind = 
/**
 *  The operating system refused access. On macOS this is usually a consent
 *  prompt that was declined.
 */
"permission-denied" | 
/**  The path could not be read for some other reason. */
"unreadable" | 
/**  A file was found but could not be understood. */
"malformed";

/**
 *  A run of text within a line.
 * 
 *  `emphasis` marks the part that actually differs, so an added line that
 *  changed one word does not read as though all of it is new.
 */
export type Segment = {
	text: string,
	emphasis: boolean,
};

/**
 *  Settings plus the tool registry they resolve to.
 * 
 *  Sent together because the frontend always needs both and they must agree:
 *  an override is meaningless without the tool it applies to.
 */
export type SettingsView = {
	settings: AppSettings,
	tools: ToolConfig[],
};

export type SiblingFile = {
	/**  Path relative to the skill's folder. */
	path: string,
	bytes: number | null,
};

export type SortOrder = "name-asc" | "name-desc" | "modified-desc" | "modified-asc";

export type ThemePref = "system" | "light" | "dark";

/**  One AI coding tool and where it keeps things. */
export type ToolConfig = {
	id: string,
	/**  Paths at the global (home directory) scope. May start with `~`. */
	paths: Partial<{ [key in ItemType]: string }>,
	/**
	 *  Project-scoped overrides. Where a type is absent here but present in
	 *  `paths`, the project path is derived by stripping the leading `~/`.
	 */
	projectPaths: Partial<{ [key in ItemType]: string }>,
	/**
	 *  Documented but unverified locations. **Never scanned** — these exist so
	 *  the tool editor can offer them as a suggestion the user opts into.
	 */
	unconfirmedPaths: Partial<{ [key in ItemType]: string }>,
	/**
	 *  Hidden from the tool grid. Still scanned: skipping it would make the
	 *  metadata store treat every one of its items as gone.
	 */
	disabled: boolean,
	/**  Added by the user rather than shipped with the app, and therefore removable. */
	custom: boolean,
	/**  `paths[Rule]` names one file, not a directory — `CLAUDE.md`, `AGENTS.md`. */
	singleFileRule: boolean,
	ruleAdditionalPaths: RulePathEntry[],
	ruleAdditionalProjectPaths: RulePathEntry[],
	/**  Subfolder names the vendor ships and the user did not write. */
	builtInDirnames: string[],
	/**  JSON registry of installed plugins (Claude Code). */
	pluginsRegistry: string | null,
	/**  Roots of a versioned plugin bundle cache (Codex). */
	pluginsPaths: string[],
	/**  JSON file holding an `enabledPlugins` map. */
	pluginsSettingsPath: string | null,
	/**
	 *  Per-bundle subfolder override, where a bundle lays things out differently
	 *  from the tool's own global paths.
	 */
	pluginPaths: Partial<{ [key in ItemType]: string }>,
	mcpConfigPath: string | null,
	projectMcpConfigPath: string | null,
	/**
	 *  Key holding the server map. Defaults to `mcpServers` (JSON) or
	 *  `mcp_servers` (TOML).
	 */
	mcpConfigKey: string | null,
	mcpConfigFormat: McpConfigFormat,
};

/**
 *  What a user may change about a tool.
 * 
 *  Absence means "whatever the application ships". Adding a field to
 *  [`ToolConfig`] does not belong here unless the user is meant to be able to
 *  override it.
 * 
 *  The path maps merge per type rather than replacing wholesale, so changing
 *  where one tool keeps its commands leaves its skills alone — and leaves them
 *  free to be corrected by an update. An **empty string** is how a type is
 *  turned off: it says "do not scan this at all", which is different from
 *  saying nothing and getting the default.
 */
export type ToolOverride = {
	paths?: Partial<{ [key in ItemType]: string }>,
	projectPaths?: Partial<{ [key in ItemType]: string }>,
	disabled?: boolean | null,
	ruleAdditionalPaths?: RulePathEntry[] | null,
	ruleAdditionalProjectPaths?: RulePathEntry[] | null,
	pluginsRegistry?: string | null,
	pluginsPaths?: string[] | null,
	pluginsSettingsPath?: string | null,
	mcpConfigPath?: string | null,
	projectMcpConfigPath?: string | null,
	mcpConfigKey?: string | null,
};

/**  One tool, with every path it would read resolved against this machine. */
export type ToolReport = {
	tool: ToolConfig,
	/**
	 *  What the application ships, before the user's changes.
	 * 
	 *  Sent alongside so a field can say what it would go back to, and
	 *  offer to.
	 */
	shipped: ToolConfig | null,
	overrides: ToolOverride,
	paths: ResolvedPath[],
	/**  Whether any of its folders is actually on this machine. */
	detected: boolean,
};

/**  What a check found out about one item. */
export type UpdateCheck = {
	entryId: string,
	status: UpdateStatus,
	/**  What the remote has now, when it could be read. */
	remoteCommit: string | null,
	/**  Why the check failed, when it did. */
	error: string | null,
};

/**  Whether a tracked item's source has moved on. */
export type UpdateStatus = 
/**  The recorded commit is still the remote's tip. */
"current" | 
/**  The remote has moved on. */
"stale" | 
/**  Not installed through this application, so there is nothing to check. */
"untracked";

/**  How far along reading a tool's history is. */
export type UsageProgress = {
	done: number,
	total: number,
};

/**  How often one thing was used, and when it last was. */
export type UsageStats = {
	count: number,
	/**  RFC 3339, or `None` if it has never been used. */
	lastUsed: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

