// @generated by tauri-specta. Do not edit by hand.
// Run `cargo test -p skills-hub` to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	probeCapabilities: () => typedError<Capabilities, CommandError>(__TAURI_INVOKE("probe_capabilities")),
};

/* Types */
export type Capabilities = {
	/**  Home directory, as the scanner will expand `~`. */
	home: string,
	/**
	 *  Whether this process may create symlinks. False on Windows without
	 *  Developer Mode, which disables linking a global skill into a project.
	 */
	symlinksSupported: boolean,
	appVersion: string,
	platform: string,
};

export type CommandError = {
	code: string,
	message: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

