// @generated by tauri-specta. Do not edit by hand.
// Run `cargo test -p skills-hub` to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	probeCapabilities: () => typedError<Capabilities, CommandError>(__TAURI_INVOKE("probe_capabilities")),
	getSettings: () => typedError<SettingsView, CommandError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Replaces the settings wholesale.
	 * 
	 *  The frontend sends the whole document because it holds the authoritative
	 *  copy between edits; a patch API would need a merge on both sides.
	 */
	updateSettings: (settings: AppSettings) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("update_settings", { settings })),
	setToolOverride: (toolId: string, overrides: ToolOverride) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("set_tool_override", { toolId, overrides })),
	/**  Points the store at a folder, creating it if need be. */
	setMetadataFolder: (folder: string) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("set_metadata_folder", { folder })),
	addProjectWorkspace: (path: string, name: string | null) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("add_project_workspace", { path, name })),
	removeProjectWorkspace: (id: string) => typedError<SettingsView, CommandError>(__TAURI_INVOKE("remove_project_workspace", { id })),
	/**
	 *  The last scan's result, without touching the disk.
	 * 
	 *  What the window asks for when it opens or reloads.
	 */
	getSnapshot: () => typedError<{
	items: ItemMetadata[],
	plugins: PluginSource[],
	brokenSymlinks: BrokenSymlink[],
	warnings: ScanWarning[],
	/**  When the scan ran, as RFC 3339 — the same form the notes use. */
	scannedAt: string,
	/**
	 *  Increments with every scan.
	 * 
	 *  The frontend keys its derived state on this, so "a scan happened"
	 *  invalidates everything at once rather than through a dozen
	 *  hand-maintained call sites.
	 */
	version: number,
	/**  Notes kept for items that are no longer on disk. */
	orphanCount: number,
} | null, CommandError>(__TAURI_INVOKE("get_snapshot")),
	/**
	 *  Walks every configured folder and records what is there.
	 * 
	 *  Runs on a blocking thread: the work is filesystem-bound, and the core is
	 *  deliberately synchronous so that it stays testable.
	 */
	rescan: (options: RescanOptions, onProgress: Channel<Progress>) => typedError<LibrarySnapshot, CommandError>(__TAURI_INVOKE("rescan", { options, onProgress })),
	/**  Notes kept for items that are no longer on disk. */
	listOrphanedMetadata: () => typedError<Orphan[], CommandError>(__TAURI_INVOKE("list_orphaned_metadata")),
	/**  Removes orphaned notes the user has decided to let go of. */
	forgetOrphanedMetadata: (entryIds: string[]) => typedError<number, CommandError>(__TAURI_INVOKE("forget_orphaned_metadata", { entryIds })),
	readItemContent: (entryId: string) => typedError<ItemContent, CommandError>(__TAURI_INVOKE("read_item_content", { entryId })),
	/**
	 *  Saves an edit to an item's own file.
	 * 
	 *  The scanner reads name and description out of the file, so the note is
	 *  refreshed from it straight away rather than waiting for the next scan.
	 */
	writeItemContent: (entryId: string, content: string) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("write_item_content", { entryId, content })),
	setItemEnabled: (entryId: string, enabled: boolean) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_enabled", { entryId, enabled })),
	setItemFavorite: (entryId: string, favorite: boolean) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_favorite", { entryId, favorite })),
	setItemTags: (entryId: string, tags: string[]) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_tags", { entryId, tags })),
	setItemCollections: (entryId: string, collections: string[]) => typedError<ItemMetadata, CommandError>(__TAURI_INVOKE("set_item_collections", { entryId, collections })),
	/**  Makes a global item visible inside a project, by symlink. */
	linkIntoProject: (entryId: string, projectId: string) => typedError<string, CommandError>(__TAURI_INVOKE("link_into_project", { entryId, projectId })),
	/**  Removes a link from a project, leaving what it pointed at alone. */
	unlinkFromProject: (entryId: string) => typedError<null, CommandError>(__TAURI_INVOKE("unlink_from_project", { entryId })),
	/**  Deletes an item from disk, and its note with it. */
	deleteItem: (entryId: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_item", { entryId })),
	/**
	 *  Shows a file in Finder, Explorer or the desktop's file manager.
	 * 
	 *  `resolve_symlink` follows a link to where it really points, which is what
	 *  someone wants when they mean to edit the skill rather than inspect the link.
	 */
	revealInFileManager: (path: string, resolveSymlink: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("reveal_in_file_manager", { path, resolveSymlink })),
	/**  Opens a path with whatever the operating system uses for it. */
	openPath: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("open_path", { path })),
};

/* Types */
/**  Everything the application remembers between runs. */
export type AppSettings = {
	schemaVersion?: number,
	/**  Where the metadata notes live. Empty until the user has chosen. */
	metadataFolder?: string | null,
	toolOverrides?: { [key in string]: ToolOverride },
	/**  Tools the user added themselves. */
	customTools?: ToolConfig[],
	projectWorkspaces?: ProjectWorkspace[],
	/**
	 *  Collection definitions only. Membership lives in each item's note, so
	 *  there is one answer to "is this item in that collection" rather than two
	 *  that can disagree.
	 */
	collections?: CollectionDef[],
	sectionOrder?: string[],
	showEmptySidebarRows?: boolean,
	defaultSortOrder?: SortOrder,
	defaultEnabledFilter?: EnabledFilter,
	theme?: ThemePref,
};

/**  A symlink whose target no longer resolves. */
export type BrokenSymlink = {
	path: string,
	/**  The link target exactly as written, which may be relative. */
	target: string,
	/**  That target resolved to an absolute path. */
	targetPath: string,
	tool: string,
	type: ItemType,
	projectId: string | null,
};

export type Capabilities = {
	/**  Home directory, as the scanner will expand `~`. */
	home: string,
	/**
	 *  Whether this process may create symlinks. False on Windows without
	 *  Developer Mode, which disables linking a global skill into a project.
	 */
	symlinksSupported: boolean,
	appVersion: string,
	platform: string,
};

/**
 *  A named grouping of items.
 * 
 *  Only the definition lives in settings. Which items belong is recorded in
 *  each item's own note, so there is one answer to the question rather than
 *  two that can disagree — and `contains(collections, "work")` in Dataview is
 *  the real answer, not a shadow of it.
 */
export type CollectionDef = {
	id: string,
	name: string,
	icon?: string | null,
};

export type CommandError = {
	code: string,
	message: string,
};

/**  What a scan found on disk, before any user metadata is attached. */
export type DiscoveredItem = {
	entryId: string,
	/**  The `SKILL.md` for a folder skill, otherwise the file itself. */
	sourcePath: string,
	/**
	 *  `source_path` with symlinks resolved. Equal to `source_path` when it is
	 *  not a link.
	 */
	realPath: string,
	tool: string,
	type: ItemType,
	/**  `None` means the global (home directory) scope. */
	projectId: string | null,
	/**  `None` means the item was not shipped inside an installed plugin. */
	pluginId: string | null,
	name: string,
	description: string,
	/**  Derived purely from which folder the item physically sits in. */
	enabled: boolean,
	/**
	 *  When the item's own file was last written, as RFC 3339.
	 * 
	 *  `None` when it could not be read — a dangling link, or a filesystem
	 *  that does not record it.
	 */
	modified: string | null,
};

export type EnabledFilter = "all" | "enabled" | "disabled";

/**
 *  One declared frontmatter key, in the order it appeared.
 * 
 *  Order is preserved so the detail view can show the block the way the author
 *  wrote it, rather than alphabetised.
 */
export type Field = {
	key: string,
	value: string,
};

/**  Provenance for an item installed through the application. */
export type InstallSource = {
	sourceRepo: string | null,
	/**  Empty string means "track the default branch". */
	sourceRef: string | null,
	/**  Empty string means the repository root is the item. */
	sourceSubpath: string | null,
	sourceCommit: string | null,
};

/**  One item's file, as the detail view needs it. */
export type ItemContent = {
	raw: string,
	/**  Every declared frontmatter key, in the order the author wrote them. */
	frontmatter: Field[],
	/**  Everything after the frontmatter. */
	body: string,
	bytes: number | null,
	/**  When the file was last written, as RFC 3339. */
	modified: string | null,
	isSymlink: boolean,
	realPath: string,
	/**  The other files in a skill's folder, if it has any. */
	siblingFiles: SiblingFile[],
};

/**  A discovered item plus everything the user has said about it. */
export type ItemMetadata = {
	tags: string[],
	favorite: boolean,
	collections: string[],
} & DiscoveredItem & InstallSource;

/**  What a discovered file *is*, from the point of view of the tool that reads it. */
export type ItemType = "skill" | "agent" | "command" | "rule";

/**  Everything the user interface needs after a scan. */
export type LibrarySnapshot = {
	items: ItemMetadata[],
	plugins: PluginSource[],
	brokenSymlinks: BrokenSymlink[],
	warnings: ScanWarning[],
	/**  When the scan ran, as RFC 3339 — the same form the notes use. */
	scannedAt: string,
	/**
	 *  Increments with every scan.
	 * 
	 *  The frontend keys its derived state on this, so "a scan happened"
	 *  invalidates everything at once rather than through a dozen
	 *  hand-maintained call sites.
	 */
	version: number,
	/**  Notes kept for items that are no longer on disk. */
	orphanCount: number,
};

export type McpConfigFormat = "json" | "toml";

/**  A note whose item is no longer on disk. */
export type Orphan = {
	entryId: string,
	name: string,
	tool: string,
	orphanedAt: string,
	hasUserData: boolean,
	path: string,
};

/**
 *  A plugin bundle installed into one of the tools.
 * 
 *  The items inside it are scanned like any others, but are not individually
 *  toggleable: a bundle is enabled or disabled as a whole, by its own tool.
 */
export type PluginSource = {
	id: string,
	name: string,
	/**  The marketplace or registry the bundle came from. */
	group: string | null,
	/**  Where this version is installed. */
	path: string,
	toolId: string,
	enabled: boolean,
	/**  Repository from the bundle manifest, GitHub only. */
	repoUrl: string | null,
};

/**
 *  How far along a scan is.
 * 
 *  Reported as it happens so a long scan shows a count rather than a spinner.
 */
export type Progress = { stage: "scanning"; 
/**  The tool or project currently being walked. */
source: string; done: number; total: number } | { stage: "recording"; done: number; total: number } | { stage: "finished" };

/**  A folder outside the home directory that is also scanned for items. */
export type ProjectWorkspace = {
	id: string,
	name: string,
	path: string,
};

/**  What to scan. */
export type RescanOptions = {
	/**
	 *  Skip the plugin bundle walk. Only for a targeted refresh; a full scan
	 *  that left bundles out would look to the store like every bundled item
	 *  had been deleted.
	 */
	skipPlugins?: boolean,
};

/**
 *  An extra rule location beyond the tool's single configured one.
 * 
 *  `single_file` is recorded when the entry is added and never re-derived: a
 *  disabled single-file rule no longer exists at its own path, so asking the
 *  filesystem later would give the wrong answer.
 */
export type RulePathEntry = {
	path: string,
	singleFile: boolean,
};

/**
 *  Something the scan could not do.
 * 
 *  Carried through to the UI rather than logged and forgotten, because a scan
 *  that silently returned less than it should must never be allowed to look
 *  like a scan that found nothing — that is the difference between a warning
 *  and deleting the user's metadata.
 */
export type ScanWarning = {
	path: string,
	tool: string | null,
	message: string,
	kind: ScanWarningKind,
};

export type ScanWarningKind = 
/**
 *  The operating system refused access. On macOS this is usually a consent
 *  prompt that was declined.
 */
"permission-denied" | 
/**  The path could not be read for some other reason. */
"unreadable" | 
/**  A file was found but could not be understood. */
"malformed";

/**
 *  Settings plus the tool registry they resolve to.
 * 
 *  Sent together because the frontend always needs both and they must agree:
 *  an override is meaningless without the tool it applies to.
 */
export type SettingsView = {
	settings: AppSettings,
	tools: ToolConfig[],
};

export type SiblingFile = {
	/**  Path relative to the skill's folder. */
	path: string,
	bytes: number | null,
};

export type SortOrder = "name-asc" | "name-desc" | "modified-desc" | "modified-asc";

export type ThemePref = "system" | "light" | "dark";

/**  One AI coding tool and where it keeps things. */
export type ToolConfig = {
	id: string,
	/**  Paths at the global (home directory) scope. May start with `~`. */
	paths: Partial<{ [key in ItemType]: string }>,
	/**
	 *  Project-scoped overrides. Where a type is absent here but present in
	 *  `paths`, the project path is derived by stripping the leading `~/`.
	 */
	projectPaths: Partial<{ [key in ItemType]: string }>,
	/**
	 *  Documented but unverified locations. **Never scanned** — these exist so
	 *  the tool editor can offer them as a suggestion the user opts into.
	 */
	unconfirmedPaths: Partial<{ [key in ItemType]: string }>,
	/**
	 *  Hidden from the tool grid. Still scanned: skipping it would make the
	 *  metadata store treat every one of its items as gone.
	 */
	disabled: boolean,
	/**  Added by the user rather than shipped with the app, and therefore removable. */
	custom: boolean,
	/**  `paths[Rule]` names one file, not a directory — `CLAUDE.md`, `AGENTS.md`. */
	singleFileRule: boolean,
	ruleAdditionalPaths: RulePathEntry[],
	ruleAdditionalProjectPaths: RulePathEntry[],
	/**  Subfolder names the vendor ships and the user did not write. */
	builtInDirnames: string[],
	/**  JSON registry of installed plugins (Claude Code). */
	pluginsRegistry: string | null,
	/**  Roots of a versioned plugin bundle cache (Codex). */
	pluginsPaths: string[],
	/**  JSON file holding an `enabledPlugins` map. */
	pluginsSettingsPath: string | null,
	/**
	 *  Per-bundle subfolder override, where a bundle lays things out differently
	 *  from the tool's own global paths.
	 */
	pluginPaths: Partial<{ [key in ItemType]: string }>,
	mcpConfigPath: string | null,
	projectMcpConfigPath: string | null,
	/**
	 *  Key holding the server map. Defaults to `mcpServers` (JSON) or
	 *  `mcp_servers` (TOML).
	 */
	mcpConfigKey: string | null,
	mcpConfigFormat: McpConfigFormat,
};

/**
 *  What a user may change about a tool.
 * 
 *  Every field is optional and absence means "whatever the application ships".
 *  Adding a field to [`ToolConfig`] does not belong here unless the user is
 *  meant to be able to override it.
 */
export type ToolOverride = {
	paths?: Partial<{ [key in ItemType]: string }> | null,
	projectPaths?: Partial<{ [key in ItemType]: string }> | null,
	disabled?: boolean | null,
	ruleAdditionalPaths?: RulePathEntry[] | null,
	ruleAdditionalProjectPaths?: RulePathEntry[] | null,
	pluginsRegistry?: string | null,
	pluginsPaths?: string[] | null,
	pluginsSettingsPath?: string | null,
	mcpConfigPath?: string | null,
	projectMcpConfigPath?: string | null,
	mcpConfigKey?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

